import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import { registerClipBundle } from './hooks/useAudioClips.js';
import './styles/index.css';

// Pre-rendered letter SOUND MP3s.  Generated by
// audio-pipeline/generate_letter_sounds.py from letter-sounds.json
// using SSML <phoneme alphabet="ipa" ...> tags so each letter renders
// the correct phoneme (e.g. S = hissing /s/ rather than spelled "ess").
//
// If a file is missing the runtime falls back to live TTS — see
// playClipIfAvailable in useAudioClips.js.  So registering the bundle
// here is safe even before the script has been run; the moment the
// MP3s land, kids automatically get the higher-quality audio.
const letterClips = {};
for (const ch of 'abcdefghijklmnopqrstuvwxyz') {
  letterClips[`letter:${ch}`] = `/audio/letters/sounds/letter-${ch}-sound.mp3`;
}
registerClipBundle(letterClips);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
