import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import { registerClipBundle } from './hooks/useAudioClips.js';
import './styles/index.css';

// Pre-rendered letter SOUND MP3s.  Generated by
// audio-pipeline/generate_letter_sounds.py from letter-sounds.json.
//
// We only register the bundle when the build actually contains the
// MP3s.  Vite inlines the result of `import.meta.glob(... { eager })`
// at build time so this is zero-cost at runtime, and dropping a fresh
// MP3 into public/audio/letters/sounds/ is enough to wire it up — no
// other code changes needed.  Until any MP3s exist, the bundle stays
// empty and runtime TTS handles letter sounds.
const letterClipModules = import.meta.glob(
  '/public/audio/letters/sounds/letter-*-sound.mp3',
  { eager: true, query: '?url', import: 'default' },
);
const letterClips = {};
for (const [path, url] of Object.entries(letterClipModules)) {
  const m = path.match(/letter-([a-z])-sound\.mp3$/);
  if (m) letterClips[`letter:${m[1]}`] = url;
}
if (Object.keys(letterClips).length) {
  registerClipBundle(letterClips);
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
